* Section 5: Hebrew as an example

** Letters

*** Handling cases of identical letter sounds

*** A Hebrew-English keymap 

** Context-specific/alternate letter forms

*** Word final letters: the sofit forms

*** The Begadkephat letters

*** Shin and Sin

** Mandatory markup

*** A note about opinionated design decisions

- "Case study" -- the /matres lectionis/ letters. Automatically including vav and yod when they are vowel indicators.

*** Basic vowel points

*** Shva and reduced vowels

*** The dagesh

** Additional markup

*** The meteg

*** Cantillation marks

** Punctuation; language-specific symbols

*** A discussion of languages that use "mostly normal" punctuation (from the English point of view)

*** The geresh

*** The gershayim (lit. "double geresh" -- this word is plural)

*** Colon and /sof pasuq/

*** Vertical bar and /paseq/

*** Hyphen and /maqaf/

*** Shekel symbol


* Typing efficiency

*** Abbreviating very frequent words and phrases

** Creating necessary resources

*** Word frequency tables

- Perseus, TLG, handling overlapping forms

*** N-gram frequency tables

- Similar process. Handling semantic boundaries in regexes? How to automate morphological analysis without obvious delimiters like spaces for words?

*** Area-specific practice texts

- Downloading from free/uncopyrighted sources. Perseus, Project Gutenberg.[fn:18]


** Creating necessary resources

*** Word frequency tables

- short term (this paper): make frequency table in a text file to use with Amphetype based on sources
- long term: Perseus, TLG, handling overlapping forms, etc. More of the methodology type stuff from DCC page. Only mention, don't discuss in depth.

*** N-gram frequency tables

- Make practice files based on common declensions and conjugations
- prepositions (which are commonly used as prefixes), inseparable prefixes (cf. Smyth section above)

- Again mention more rigorous ways to do this in future. Data driven, statistical. But don't elaborate much.

*** Area-specific practice texts

- Downloading from free/uncopyrighted sources. Perseus.
- Hiccup of precomposed/decomposed. Perseus texts are precomposed, so can be used for typing practice when in precomposed mode.
- Removing numbers, footnotes. Regexes. Temporary. Use web scraping or Perseus API eventually. Here just minimal working example for proof opf concept.

** Typing practice

*** Amphetype

Screenshots. Typing sources directly. Disable all sources then enable one by one.

Challenges of Unicode not matching text when precomposed. Not that important, but error metrics will be thrown off.

Future ideal: make texts convertible between forms at the press of the button, and practice in decomposed so that error statistics are correct.

*** Lesson generation from frequency tables and practice texts

Paste in/load, generate.

link to Java script [[https://github.com/StevenTammen/amphetype-texts/blob/master/src/FrequencyLists.java][in separate repository]] for English example. Future: get Greek frequencies and do something similar. Explain idea behind it: want words repeated according to their relative frequencies. In typing practice corpora. If you have a corpus consisting of 3 words (word1 = 60%, word2 = 30%, word3 = 10%), then for every 10 words you type, you would want about 6 word1's, 3 word2's, and 1 word3.


* Later work
** Integrating general electronic/online resources into classes

***  Language input as a pain point

- A lack of good keyboard input is a significant damper to the use of electronic/online resources.

*** The value of electronic/online resources

\noindent *Elecronic lexica and morphology parsers* \\

Dangers of over-reliance, but great benefits all the same. Arbitrary searches (those that require the ability to type native text) can be necessary when using paper sources rather than cross-linked sources like those on Perseus. \\

\noindent *Searches* \\

- Fuzzy search (i.e., lemma search), finding passages and references, searching on word usage or specific form.
- Searching typed notes, if people type class notes \\

\noindent *Electronic flashcards* \\

More polarizing whether or not they are useful, but making them easier to construct is definitely a good thing. Spaced repetition studying, Anki. \\

\noindent *Autograded sentences* \\

-	Practicing typing in general by providing form-fields to enter sentence translations. Depending on the difficulty of implementation, it might be possible to create an autograder for practice sentences in Athenaze, for example. If care was taken to follow vocabulary acquisition (so as to limit the lexicon input for the program and make it deterministic), it would be easy for professors to design supplemental/optional practice exercises that the students could complete with instant feedback and no extra work for the professor.

** Word Processing

*** Font testing: Gentium Plus + SBL Hebrew

Here is some inline Hebrew from the beginning of Genesis 1 \texthebrew{‏בְּרֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ׃ ‎2‏ וְהָאָ֗רֶץ הָיְתָ֥ה תֹ֨הוּ֙ וָבֹ֔הוּ וְחֹ֖שֶׁךְ עַל־פְּנֵ֣י תְה֑וֹם וְר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל־פְּנֵ֥י הַמָּֽיִם׃ ‎3‏ וַיֹּ֥אמֶר אֱלֹהִ֖ים יְהִ֣י א֑וֹר וַֽיְהִי־אֽוֹר׃ ‎4‏ וַיַּ֧רְא אֱלֹהִ֛ים אֶת־הָא֖וֹר כִּי־ט֑וֹב וַיַּבְדֵּ֣ל אֱלֹהִ֔ים בֵּ֥ין הָא֖וֹר וּבֵ֥ין הַחֹֽשֶׁךְ׃} with English around it. And now a block:

#+BEGIN_QUOTE
\begin{hebrew}
‏‏בְּרֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ׃ ‎2‏ וְהָאָ֗רֶץ הָיְתָ֥ה תֹ֨הוּ֙ וָבֹ֔הוּ וְחֹ֖שֶׁךְ עַל־פְּנֵ֣י תְה֑וֹם וְר֣וּחַ אֱלֹהִ֔ים מְרַחֶ֖פֶת עַל־פְּנֵ֥י הַמָּֽיִם׃ ‎3‏ וַיֹּ֥אמֶר אֱלֹהִ֖ים יְהִ֣י א֑וֹר וַֽיְהִי־אֽוֹר׃ ‎4‏ וַיַּ֧רְא אֱלֹהִ֛ים אֶת־הָא֖וֹר כִּי־ט֑וֹב וַיַּבְדֵּ֣ל אֱלֹהִ֔ים בֵּ֥ין הָא֖וֹר וּבֵ֥ין הַחֹֽשֶׁךְ׃
\end{hebrew}
#+END_QUOTE

And here is some inline Greek from the /Iliad/ μῆνιν ἄειδε θεὰ Πηληϊάδεω Ἀχιλῆος with English around it. And now a longer chunk:

#+BEGIN_QUOTE
μῆνιν ἄειδε θεὰ Πηληϊάδεω Ἀχιλῆος οὐλομένην, ἣ μυρί᾽ Ἀχαιοῖς ἄλγε᾽ ἔθηκε, πολλὰς δ᾽ ἰφθίμους ψυχὰς Ἄϊδι προΐαψεν ἡρώων, αὐτοὺς δὲ ἑλώρια τεῦχε κύνεσσιν οἰωνοῖσί τε πᾶσι, Διὸς δ᾽ ἐτελείετο βουλή, ἐξ οὗ δὴ τὰ πρῶτα διαστήτην ἐρίσαντε Ἀτρεΐδης τε ἄναξ ἀνδρῶν καὶ δῖος Ἀχιλλεύς. τίς τ᾽ ἄρ σφωε θεῶν ἔριδι ξυνέηκε μάχεσθαι;
#+END_QUOTE

*** Reasons why something other than Word might be desirable

- Automatic font use rather than manual switching

*** Example: Emacs' Org mode to PDF using XeLaTeX

- Support for RTL languages and automatic display
- Polyglossia
- Automatic font switches

*** Yudit?

{Todo: [fn:19]}

** Abbreviations

- More of a personal thing. Can algorithmically generate in theory. (Outside scope of this project).
- Probably good to look at the 10 or 15 most common words and see if anything jumps out at you
- Creating regex hotstrings in this particular AHK implementation.

* Pedagogy

** Orthography for digital natives

*** Standardization of letterforms

- Reducing the learning load in the first few weeks of Hebrew: block scripts and cursive scripts.
- Possible in handwritten as well (just only writing in block)

*** Typing speed and writing speed

*** But the permanence of handwriting

- Tests
- Handwritten forms and memory (??). Footnote as possible reason for continuing handwriting.


*** Interfacing to computer programs

While it is perfectly possible for professors to use CALL software to generate printable worksheets etc. for their students, any student-driven learning will have to go through computers.

The dynamic possibilities are what is of interest. Having a student enter a word that they want to practice, and generating practice forms relating to that, e.g.

** Some specific examples

Now that the general reasoning has been laid out, it will be helpful to examine several examples of combining typing and Greek language learning. Going through the word frequency list without additional structure is certainly a possibility, but it will be of benefit for beginning students to focus on those words that line up with what they are currently learning. 

*** Learning the alphabet; practicing reading/speaking Greek; "reading by typing"

- Familiarity with alphabet and sounds is a big hurdle the first few weeks. Hard to remember vocabulary before fully comfortable with alphabet. (Research of possible? Definitely true for me for both Greek and Hebrew, and others I've talked to).
- Learn how to type letters while learning about their sounds, etc. Creating form (orthography), sound (phonetics), and motor (typing finger position) associations.
-	Practicing typing in general by pulling in Greek texts from Perseus as typing training material. Students could be encouraged to also read the texts out loud as they type them. (Not necessarily understanding the Greek, but getting to see how it sounds and flows).

*** Learning standard declensions and conjugations

- 1st, 2nd, 3rd declension nouns. All three genders.
- Adjectives
- Participles
- Verbs (omega verbs, contract verbs, mi-verbs, etc.)

This would be one of the biggest pedagogical applications: learn how to type all the basic language structures as you learn the forms for them. Typing them forces you to see them, and gives you the structured practice.

*** Learning other common paradigms

Some things have to be brute forced. Irregular verbs, relative pronouns, definite articles, indefinite/interrogative pronouns, etc.

Similar principles for these.

*** Learning the accentuation system

- Practicing the typing of accents while learning about the rule of contonation, morae, and recessive accents.

*** Morphological analysis and generative vocabulary

- Prefixes, suffixes, and roots. Developing an eye for picking up meanings automatically, simply by knowing what different parts of the word mean in general.

*** Vocabulary lists by frequency for specific domains

Past core vocabulary, domain specific vocabulary can be useful

*** Practicing typing specific groups of texts

Like vocabulary but more general. Frequent clusters/combinations of words, and "feel" for authors.

** How different levels of Greek knowledge changes the relationship

*** Beginning students getting more inherent benefit

- Beginning students who need to learn forms etc. have more inherent overlap between typing efficiency and pedagogy. Getting the 1st declension noun endings into typing muscle memory for experienced Greek scholars has less inherent benefit than the same exercise for people new to Greek, because the latter both learn the endings and become mechanically adept at entering them, while the former are only gaining the net benefit of becoming mechanically adept at entering them.
- Does not mean that experienced Greek scholars should not practice by endings (frequency considerations etc. from above -- still fastest way to improve speed and whatnot), but simply that they do not get the same degree of overlapping benefits as people newer to Greek.
- Never hurts to review endings however

*** Pedagogy benefits that do not fade as much with experience

Last three areas of overlap have longer term applicability:

- generative vocabulary always helpful
- domain-specific vocabulary
- typing specific texts: exposure as important, context, etc.
